name: SalsaEventTracker
options:
  bundleIdPrefix: com.salsaeventtracker
  minimumXcodeGenVersion: "2.18.0"
  createIntermediateGroups: true
packages:
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"
targets:
  SalsaEventTracker:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SalsaEventTracker
    settings:
      base:
        SWIFT_VERSION: "5.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.salsaeventtracker.ios
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        INFOPLIST_FILE: SalsaEventTracker/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "13"
        DEVELOPMENT_TEAM: MG3K52T7N9
    dependencies:
      - package: KeychainAccess

  SalsaEventTrackerTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SalsaEventTrackerTests
    settings:
      base:
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: SalsaEventTracker
